[package]
name = "typst-renderer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
typst = "0.14.0"
typst-render = "0.14.0"
wasm-bindgen = "0.2.105"
web-sys = { version = "0.3.82", features = ["console"] }
